### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by nonva** [SamLynnEvans/Transformer#17]
Traceback (most recent call last):  ]  0%  loss = ...
  File "train.py", line 183, in <module>
    main()
  File "train.py", line 111, in main
    train_model(model, opt)
  File "train.py", line 34, in train_model
    src_mask, trg_mask = create_masks(src, trg_input, opt)
  File "/dockerdata/bert_seq2seq/Transformer-master/Batch.py", line 25, in create_masks
    trg_mask = trg_mask & np_mask
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_and

how to solve the problem

**Comment by MehwishFatimah** [comment]
np_mask = np_mask.cuda()
trg_mask = trg_mask.cuda()
trg_mask = trg_mask & np_mask

It will resolve the issue, hopefully.

**Comment by sunchipsster1** [comment]
Hello! I also have the same problem. I tried the solution proposed by Mehwish Fatimah, and the following error (image below) still persists. Any help would be very much appreciated, thank you!

![image](https://user-images.githubusercontent.com/56416888/85818887-de61de80-b73f-11ea-97f0-96a2d005bb4d.png)

**Comment by MehwishFatimah** [comment]
> Traceback (most recent call last): ] 0% loss = ...
> File "train.py", line 183, in
> main()
> File "train.py", line 111, in main
> train_model(model, opt)
> File "train.py", line 34, in train_model
> src_mask, trg_mask = create_masks(src, trg_input, opt)
> File "/dockerdata/bert_seq2seq/Transformer-master/Batch.py", line 25, in create_masks
> trg_mask = trg_mask & np_mask
> RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_and
> 
> how to solve the problem

Check your device, I would suggest to pass it as a parameter in all function calls to avoid device conflict.
