### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shibin2018** [SamLynnEvans/Transformer#21]
F:\Anaconda\envs\Transformer-master\python.exe E:/Transformer-master/train.py -src_data english.txt -trg_data french.txt -src_lang en -trg_lang fr -epochs 10
loading spacy tokenizers...
Traceback (most recent call last):
  File "E:/Transformer-master/train.py", line 184, in <module>
    main()
  File "E:/Transformer-master/train.py", line 96, in main
    SRC, TRG = create_fields(opt)
  File "E:\Transformer-master\Process.py", line 35, in create_fields
    t_src = tokenize(opt.src_lang)
  File "E:\Transformer-master\Tokenize.py", line 7, in __init__
    self.nlp = spacy.load(lang)
  File "F:\Anaconda\envs\Transformer-master\lib\site-packages\spacy\__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "F:\Anaconda\envs\Transformer-master\lib\site-packages\spacy\util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by JennieCheng** [comment]
+1

**Comment by donglinz** [comment]
@shibin2018 @JennieCheng Try this:
python -m spacy download en

**Comment by IDWAGirl** [comment]
The problem still exists. What should I do

**Comment by kijlk** [comment]
you can use :
"fr_core_news_sm" instead of "fr"
"en_core_web_sm" instead of "en"
eg:
    t_src = tokenize("fr_core_news_sm")
    t_trg = tokenize("en_core_web_sm")
